name: Run Django Tests
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  test:
    name: Run Django Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8"]
        django-version: ["3.2", "4.0", "4.1b1"]
        include:
          - python-version: "3.6"
            django-version: "3.2"
          - python-version: "3.7"
            django-version: "3.2"

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          cache: "pip"
          cache-dependency-path: "setup.cfg"
          python-version: ${{ matrix.python-version }}

      - run: pip install -U pip wheel
      - run: pip install django==${{ matrix.django-version }} -e .

      - name: Run tests
        run: django-admin test -v2
        env:
          DJANGO_SETTINGS_MODULE: tests.settings
